pokemon_list = [
    "MissingNo.",
    "Rhydon", "Kangaskhan", "Nidoran♂", "Clefairy", "Spearow", "Voltorb", 
    "Nidoking", "Slowbro", "Ivysaur", "Exeggutor", "Lickitung", "Exeggcute", 
    "Grimer", "Gengar", "Nidoran♀", "Nidoqueen", "Cubone", "Rhyhorn", "Lapras", 
    "Arcanine", "Mew", "Gyarados", "Shellder", "Tentacool", "Gastly", "Scyther", 
    "Staryu", "Blastoise", "Pinsir", "Tangela", "MissingNo.", "MissingNo.", 
    "Growlithe", "Onix", "Fearow", "Pidgey", "Slowpoke", "Kadabra", "Graveler", 
    "Chansey", "Machoke", "Mr. Mime", "Hitmonlee", "Hitmonchan", "Arbok", "Parasect", 
    "Psyduck", "Drowzee", "Golem", "MissingNo.", "Magmar", "MissingNo.", "Electabuzz", 
    "Magneton", "Koffing", "MissingNo.", "Mankey", "Seel", "Diglett", "Tauros", "MissingNo.", 
    "MissingNo.", "MissingNo.", "Farfetch'd", "Venonat", "Dragonite", "MissingNo.", 
    "MissingNo.", "MissingNo.", "Doduo", "Poliwag", "Jynx", "Moltres", "Articuno", "Zapdos", 
    "Ditto", "Meowth", "Krabby", "MissingNo.", "MissingNo.", "MissingNo.", "Vulpix", 
    "Ninetales", "Pikachu", "Raichu", "MissingNo.", "MissingNo.", "Dratini", "Dragonair", 
    "Kabuto", "Kabutops", "Horsea", "Seadra", "MissingNo.", "MissingNo.", "Sandshrew", 
    "Sandslash", "Omanyte", "Omastar", "Jigglypuff", "Wigglytuff", "Eevee", "Flareon", 
    "Jolteon", "Vaporeon", "Machop", "Zubat", "Ekans", "Paras", "Poliwhirl", "Poliwrath", 
    "Weedle", "Kakuna", "Beedrill", "MissingNo.", "Dodrio", "Primeape", "Dugtrio", "Venomoth", 
    "Dewgong", "MissingNo.", "MissingNo.", "Caterpie", "Metapod", "Butterfree", "Machamp", 
    "MissingNo.", "Golduck", "Hypno", "Golbat", "Mewtwo", "Snorlax", "Magikarp", "MissingNo.", 
    "MissingNo.", "Muk", "MissingNo.", "Kingler", "Cloyster", "MissingNo.", "Electrode", 
    "Clefable", "Weezing", "Persian", "Marowak", "MissingNo.", "Haunter", "Abra", "Alakazam", 
    "Pidgeotto", "Pidgeot", "Starmie", "Bulbasaur", "Venusaur", "Tentacruel", "MissingNo.", 
    "Goldeen", "Seaking", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "Ponyta", "Rapidash", 
    "Rattata", "Raticate", "Nidorino", "Nidorina", "Geodude", "Porygon", "Aerodactyl", 
    "MissingNo.", "Magnemite", "MissingNo.", "MissingNo.", "Charmander", "Squirtle", 
    "Charmeleon", "Wartortle", "Charizard", "MissingNo.", "MissingNo.", "MissingNo.", "MissingNo.", "Oddish", 
    "Gloom", "Vileplume", "Bellsprout", "Weepinbell", "Victreebel",
]
idToText = [
    "␀"," "," "," "," "," "," "," "," "," "," "," "," "," "," "," ", #Row 0
    " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," ", #Row 1
    " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," ", #Row 2
    " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," ", #Row 3
    " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," ", #Row 4
    " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," ", #Row 5
    "A","B","C","D","E","F","G","H","I","V","S","L","M",":","ぃ","ぅ", #Row 6
    "‘","’","“","”","・","…","ぁ","ぇ","ぉ","╔","═","╗","║","╚","╝","␠", #Row 7
    "A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P", #Row 8
    "Q","R","S","T","U","V","W","X","Y","Z","(",")",":",";","[","]", #Row 9
    "a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p", #Row A
    "q","r","s","t","u","v","w","x","y","z","é","'d","'l","'s","'t","'v", #Row B
    " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," ", #Row C
    " "," "," "," "," "," "," "," "," "," "," "," "," "," "," "," ", #Row D
    "'","PK","MN","-","'r","'m","?","!",".","ァ","ゥ","ェ","▷","▶","▼","♂", #Row E
    "P$","×",".","/",",","♀","0","1","2","3","4","5","6","7","8","9", #Row F
]
glitch_pokemon_list = [
    "▶ A", "a", "ゥ (C1)", "ゥ .4", "h POKé", 
    "PokéWTrainer", "PKMN (C5)", "ゥL ゥM 4", "♀Pゥ ゥゥT", 
    "ゥU?", "◣ゥ 8", "PC4SH", "p", "PKMN ◣ n", 
    "Trainer", "▼ W G d", "OPKMN4X", "PKMN PKMN T", "4B 8 4 8", 
    "ゥ '", "M p'u ゥ", "Aゥ G", "Pゥ ゥ ゥ", "4 h", 
    "Glitch (D7)", "PKMNaPKMNゥ ♂ fPKMNk", "PKMNRPKMN \"", "B (DA)", "Glitch (DB)", 
    "Glitch (DC)", "7PKMN 'v", "-PKMN", ".PKMN", "/PKMN ▼PKMN", 
    "'v", "……", "ゥ (E3)", "Glitch (E4)", "C", 
    "- -", "Pゥ 4$", "X C", "c", "A (EA)", 
    "Glitch (EB)", "Glitch (EC)", "hゥ", ".g", "ゥ$'M", 
    "ゥ$ (F0)", "94", "ゥ l (F2)", "ゥ l (F3)", "ゥ$ (F4)", 
    "ゥ (F5)", "G'Mp", "'Ng'Mp", "'Ng ゥ$", "94 h", 
    "Glitch (FA)", "'M 'N g", "O", "ゥ$ 6ゥ", 
    "'M (FE)", "'M (FF)"
]


#	Name	Type	Category	PP	Power	Accuracy	Gen
moves_list = [
"",
"Pound",
"Karate Chop",
"Double Slap",
"Comet Punch",
"Mega Punch",
"Pay Day",
"Fire Punch",
"Ice Punch",
"Thunder Punch",
"Scratch",
"Vise Grip",
"Guillotine",
"Razor Wind",
"Swords Dance",
"Cut",
"Gust",
"Wing Attack",
"Whirlwind",
"Fly",
"Bind",
"Slam",
"Vine Whip",
"Stomp",
"Double Kick",
"Mega Kick",
"Jump Kick",
"Rolling Kick",
"Sand Attack",
"Headbutt",
"Horn Attack",
"Fury Attack",
"Horn Drill",
"Tackle",
"Body Slam",
"Wrap",
"Take Down",
"Thrash",
"Double-Edge",
"Tail Whip",
"Poison Sting",
"Twineedle",
"Pin Missile",
"Leer",
"Bite",
"Growl",
"Roar",
"Sing",
"Supersonic",
"Sonic Boom",
"Disable",
"Acid",
"Ember",
"Flamethrower",
"Mist",
"Water Gun",
"Hydro Pump",
"Surf",
"Ice Beam",
"Blizzard",
"Psybeam",
"Bubble Beam",
"Aurora Beam",
"Hyper Beam",
"Peck",
"Drill Peck",
"Submission",
"Low Kick",
"Counter",
"Seismic Toss",
"Strength",
"Absorb",
"Mega Drain",
"Leech Seed",
"Growth",
"Razor Leaf",
"Solar Beam",
"Poison Powder",
"Stun Spore",
"Sleep Powder",
"Petal Dance",
"String Shot",
"Dragon Rage",
"Fire Spin",
"Thunder Shock",
"Thunderbolt",
"Thunder Wave",
"Thunder",
"Rock Throw",
"Earthquake",
"Fissure",
"Dig",
"Toxic",
"Confusion",
"Psychic",
"Hypnosis",
"Meditate",
"Agility",
"Quick Attack",
"Rage",
"Teleport",
"Night Shade",
"Mimic",
"Screech",
"Double Team",
"Recover",
"Harden",
"Minimize",
"Smokescreen",
"Confuse Ray",
"Withdraw",
"Defense Curl",
"Barrier",
"Light Screen",
"Haze",
"Reflect",
"Focus Energy",
"Bide",
"Metronome",
"Mirror Move",
"Self-Destruct",
"Egg Bomb",
"Lick",
"Smog",
"Sludge",
"Bone Club",
"Fire Blast",
"Waterfall",
"Clamp",
"Swift",
"Skull Bash",
"Spike Cannon",
"Constrict",
"Amnesia",
"Kinesis",
"Soft-Boiled",
"High Jump Kick",
"Glare",
"Dream Eater",
"Poison Gas",
"Barrage",
"Leech Life",
"Lovely Kiss",
"Sky Attack",
"Transform",
"Bubble",
"Dizzy Punch",
"Spore",
"Flash",
"Psywave",
"Splash",
"Acid Armor",
"Crabhammer",
"Explosion",
"Fury Swipes",
"Bonemerang",
"Rest",
"Rock Slide",
"Hyper Fang",
"Sharpen",
"Conversion",
"Tri Attack",
"Super Fang",
"Slash",
"Substitute",
"Struggle",
]

typeList = [
    "Normal",
    "Fighting",
    "Flying",
    "Poison",
    "Ground",
    "Rock",
    "Bird",
    "Bug",
    "Ghost",
    "Normal",
    "Normal",
    "Normal",
    "Normal",
    "Normal",
    "Fire",
    "Water",
    "Grass",
    "Electric",
    "Psychic",
    "Ice",
    "Dragon"
]
'''
print(len(idToText))

for i in range(0,0xf):
    line = ""
    for count in range(0,0xf):
        line += idToText[count+i*0x10]
    print(f"LINE {hex(i)}: {line}")
'''